nuxeo:
  image: nuxeo:9.10
  ports:
    - "9081:8080"
    - "8787:8787"
  environment:
      NUXEO_PACKAGES: nuxeo-jsf-ui
      NUXEO_TEMPLATES: "\\/opt\\/nuxeo\\/config\\/custom"
      NUXEO_INSTALL_HOTFIX: "false"
  volumes:
    - /home/pgmillon/instance-pgm.clid:/var/lib/nuxeo/data/instance.clid
    - ./docker/nuxeo/nuxeo.conf:/nuxeo.conf
    - ./docker/nuxeo/nuxeo.defaults:/opt/nuxeo/config/custom/nuxeo.defaults
    - ./docker/nuxeo/custom-config.xml:/opt/nuxeo/config/custom/nxserver/config/custom-config.xml

php:
  build: docker/php-fpm
  links:
    - nuxeo
  volumes:
    - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    - ./:/var/www/html:rw

nginx:
  image: nginx:stable
  links:
    - php
  ports:
    - "9080:80"
  volumes:
    - ./docker/nginx/localhost.lan.conf:/etc/nginx/conf.d/localhost.lan.conf
    - ./:/var/www/html
