name: Functional tests

on:
  pull_request:
    paths:
      - src/**
      - ftests/**

jobs:
  ftests:
    runs-on: ubuntu-latest
    services:
      nuxeo:
        image: "nuxeo:9.10"
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.1"
          tools: composer
      - run: composer install
      - run: php vendor/bin/phpunit --group server
